#Create a User
POST http://localhost:8080/userservice/api/v1/users
Content-Type: application/json

{
  "firstName": "Hossein",
  "lastName": "Rostami",
  "mail":    "hossein.rsty@rwu.de"
}
###
#Create a User 2
POST http://localhost:8080/userservice/api/v1/users
Content-Type: application/json

{
  "firstName": "Max",
  "lastName": "Mustermann",
  "mail":    "max@web.de"
}

###
# Get All Users
GET http://localhost:8080/userservice/api/v1/users

###################################
#Create a Trip
POST http://localhost:8080/tripservice/api/v1/trips
Content-Type: application/json

{
  "name": "KCD Munich",
  "destination": "Munich",
  "startDate":    "2023-08-01",
  "endDate":    "2023-08-07",
  "purpose":    "attending as a speaker"
}
###
#Create a Trip 2
POST http://localhost:8080/tripservice/api/v1/trips
Content-Type: application/json

{
  "name": "CloudExpo",
  "destination": "Frankfurt",
  "startDate":    "2023-08-05",
  "endDate":    "2023-08-12",
  "purpose":    "attending as a visitor"
}

###
# Get All Trips
GET http://localhost:8080/tripservice/api/v1/trips

###################################

#Create an Expense
POST http://localhost:8080/expenseservice/api/v1/expenses
Content-Type: application/json

{
  "name": "Flight Tickets",
  "category": "AIRFARE",
  "amount":    "500",
  "currency":    "EUR",
  "description":    "Flight Tickets"
}
###
#Create an Expense 2
POST http://localhost:8080/expenseservice/api/v1/expenses
Content-Type: application/json

{
  "name": "Hotel",
  "category": "ACCOMMODATION",
  "amount":    "1500",
  "currency":    "EUR",
  "description":    "Hotel"
}

###
# Get All Expenses
GET http://localhost:8080/expenseservice/api/v1/expenses

###################################

#Create a doc
POST http://localhost:8080/docservice/api/v1/docs
Content-Type: application/json

{
  "name": "Flight bill",
  "docType": "JPG",
  "url":    "https://images.examples.com/wp-content/uploads/2017/06/Travel-Invoice-Template.jpg?width=320"
}
###
#Create a doc 2
POST http://localhost:8080/docservice/api/v1/docs
Content-Type: application/json

{
  "name": "Hotel bill",
  "docType": "JPG",
  "url":    "https://vencru.com/wp-content/uploads/2020/08/sample-invoice-template.png"
}

###
# Get All docs
GET http://localhost:8080/docservice/api/v1/docs

######
#Assign a Trip to a User
###PUT http://localhost:8080/tripservice/api/v1/trips/TripId,UserId
#Assign an Expense to a Trip
###PUT http://localhost:8080/tripservice/api/v1/trips/TripId,ExpenseId
DELETE http://localhost:8080/docservice/api/v1/docs/delete/64b864a0ae66a31cc216f47d

###
#Assign a Trip to a User
###PUT http://localhost:8080/tripservice/api/v1/trips/assignuser/TripID,UserID
PUT http://localhost:8080/tripservice/api/v1/trips/assignuser/64b8644fb1c8333c5f243e61,64b8642c9d78395ef482032f
###
#Assign an Expense to a Trip
###PUT http://localhost:8080/tripservice/api/v1/trips/assignexpense/TripID,ExpenseID
PUT http://localhost:8080/tripservice/api/v1/trips/assignexpense/64b8644fb1c8333c5f243e61,64b86469be6358023e6e9b7c
###
#Assign a doc(Bill) to an Expense
###PUT http://localhost:8080/expenseservice/api/v1/expenses/ExpenseID,DocID
PUT http://localhost:8080/expenseservice/api/v1/expenses/64b86469be6358023e6e9b7c,64b864d2ae66a31cc216f47e
